package net.sf.xplanner.domain;

// Generated 16-Nov-2009 23:34:52 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotificationReceiversId generated by hbm2java
 */
@Embeddable
public class NotificationReceiversId implements java.io.Serializable {

	private int projectId;
	private int personId;

	public NotificationReceiversId() {
	}

	public NotificationReceiversId(int projectId, int personId) {
		this.projectId = projectId;
		this.personId = personId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "person_id", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotificationReceiversId))
			return false;
		NotificationReceiversId castOther = (NotificationReceiversId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& (this.getPersonId() == castOther.getPersonId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getPersonId();
		return result;
	}

}
