package net.sf.xplanner.domain;

// Generated 16-Nov-2009 23:34:52 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonRoleId generated by hbm2java
 */
@Embeddable
public class PersonRoleId implements java.io.Serializable {

	private int roleId;
	private int personId;
	private int projectId;

	public PersonRoleId() {
	}

	public PersonRoleId(int roleId, int personId, int projectId) {
		this.roleId = roleId;
		this.personId = personId;
		this.projectId = projectId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "person_id", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonRoleId))
			return false;
		PersonRoleId castOther = (PersonRoleId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getPersonId() == castOther.getPersonId())
				&& (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
